title: "Raymond Tana"
description: "My CV and Projects"
author: "Raymond Tana"
baseurl: "" 
custom_css: my_assets/css/custom.css

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: pages #posts
    values:
      layout: single
      author_profile: true
      # read_time: true
      # comments: # true
      # share: true
      # related: true


# use this when remote
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# use this when not remote
# theme: minimal-mistakes-jekyll