title: "Raymond Tana"
description: "My CV and Projects"
author: "Raymond Tana"
baseurl: "" 
# custom_css: assets/css/custom.css
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
# theme: minimal-mistakes-jekyll